title: "Mon super site Jekyll"
description: "Site perso avec th√®me custom"
baseurl: "" # utile si sous-domaine
url: "https://iffigues.github.io"

# Supprime ou commente cette ligne si elle existe :
# theme: minima

plugins:
  - jekyll-feed # facultatif
excerpt_separator: ""
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - _site
