name: Check Links

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # S'ex√©cute tous les lundis √† 8h00 UTC (Cron)
    - cron: '0 8 * * 1'
  workflow_dispatch: # Permet de lancer l'action manuellement

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          # On v√©rifie ton site en ligne pour tester les liens internes ET externes
          args: --verbose --no-progress "https://iffigues.github.io"
          fail: true # Fait √©chouer l'action si un lien est mort

      - name: Create Issue From Failure
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "üîó Alerte : Liens morts d√©tect√©s"
          content-filepath: ./lychee/out.md
          labels: bug